# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 14, 18, 47, 2, 947838, tzinfo=utc)),
        ),
    ]
